# Generated by Django 4.2.4 on 2023-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expense_amount_profile_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='options',
            new_name='expense_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
